name: Greetings

on:
  pull_request_target:
  issues:
    types:
      - opened

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Check first interaction
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "👋 Welcome! We're excited to see you here and appreciate your contribution. If you need any assistance or have any questions, feel free to ask."
          pr-message: "🎉 Welcome! Your first pull request is awesome! Thank you for contributing to our project. Our team will review it shortly. If you have any questions or need further assistance, please let us know. Keep up the great work!"
