name: Package.json Check

on:
  pull_request:
    branches:
      - '*'

jobs:
  packagejson-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if package.json is modified
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -qE '^package.json$'; then
            echo "Package.json has been modified"
          else
            echo "::error::Package.json has not been modified"
            exit 1
          fi
