name: Check package.json
on:
  pull_request:
    types: [opened, edited]

jobs:
  check_package_json:
    name: Check package.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get package info
        uses: codex-team/action-nodejs-package-info@v1.1
        id: package
      - name: Check if package.json has been edited
        run: |
          old_version=$(cat package.json | grep -Po '"version": "(.*?)"')
          new_version=$(steps.package.outputs.version)
          if [ "$old_version" != "$new_version" ]; then
            echo "Package.json has been edited."
          else
            echo "Package.json has not been edited."
          fi
